Repository janiksudo/PDS_Project, pull requests merged in 2020-06, with the labels that each got.

#19 #17 Added hexmap notebook for visualization of start and end locations.
  notebooks/#17_visualize_starts_ends_hexmap.ipynb
Labels: 02 Visualization

#28 #4 Cleaned up and renamed the notebook. Improved visualization.
  notebooks/#4-visualize-#bikes-at-stations.ipynb
  notebooks/tim-#4-visualize-#bikes-at-stations.ipynb
  reports/figures/bike_availability_20092019_1200.html
Labels: 02 Visualization

#29 #8 predict the trip direction
  notebooks/#8_predict_trip_direction.ipynb
Labels: 03 Prediction

#30 #21 predict number bookings
  notebooks/predict_number_bookings.ipynb
Labels: 03 Prediction

#41 Add jupyter as a dependency
  README.md
  environment.yml
Labels: refactoring
